POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvbmphIiwiaWQiOiI2NDU0MjViNjQ4M2Y4OGJiMWY2YTU3NmEiLCJpYXQiOjE2ODQyNzMyMTZ9.ZanKXPRqjpl0DJcPuZtwmjijSBWldFGz72Av5dvly5w

{
  "title": "My crappy 4th blog",
  "author": "some other guy",
  "url": "www.mycrappyblog.com.au",
  "likes": 69
}